name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v3

      - name: Instalação do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalação das dependências
        run: npm install

      - name: Adicionar repositório do k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update

      - name: Instalação do k6
        run: sudo apt-get install -y k6

      - name: Executar os testes de api
        run: npm test

      - name: Executar os testes de performance 
        run: for file in tests/performance/**/*.js; do k6 run "$file"; done
